server:
  port: 8080

spring:
  jpa:
    database: oracle
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))(LOAD_BALANCE = yes))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl)(FAILOVER_MODE =(TYPE = SELECT)(METHOD = BASIC)(RETRIES = 180)(DELAY = 5))))
    username: zeyin
    password: zeyin
    driver-class-name: oracle.jdbc.driver.OracleDriver

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml